@base-url = {{$dotenv %URL}}:{{$dotenv %PORT}}
@api-url = {{base-url}}/api/chokomemo

###
{{base-url}}/status

###
POST {{api-url}}/login
content-type: application/json

{
    "loginId": "{{$dotenv %LoginId}}",
    "password": "{{$dotenv %Password}}"
}

###
GET {{api-url}}/all-memos
content-type: application/json

{
    "userId": "1",
    "token": "5bd57cdef6df9c8e9cf5aad4230b58a9bae34ca023d6efc009357d838baae2f2"
}

# DB-TEST

###
GET {{api-url}}/db-test
content-type: application/json

{
}

###
POST {{api-url}}/db-test
content-type: application/json

{
    "Title": "memo-title",
    "Content": "blah blah"
}